FROM condaforge/linux-anvil-comp7
RUN export PATH="/opt/conda/bin:${PATH}" && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge

