FROM alpine:3.7

RUN apk add --update \ 
    cmake \
    clang \
    clang-dev \
    make \
    gcc \
    g++ \
    libc-dev \
    linux-headers \
    python3 \
    bash \
    zlib-dev \
    bzip2-dev \
    boost-dev \
    py-sphinx \
    libexecinfo-dev

    
WORKDIR /package

